### ISSUE TITLE
Error 502 when opening web-interface

### ISSUE THREAD

**Issue by michael5411** [hassio-addons/addon-jupyterlab#322] opened 2022-09-13 09:32 UTC
# Problem/Motivation
> Did use the addon for about 12 months, but it was lost after an update.

## Actual behavior
> with any click on "open web interface" I get an error 502.

## Steps to reproduce
> Cleared cache - no change
> Delete - new install - no change

I think, there is nothing that one can do wrong by using the addon-installation? 
Just install and start. there is no config needed to get the addon startet.

So seems to be a real bug?

**Comment by tjorim** [comment] 2022-09-13 17:00
Probably duplicate of https://github.com/hassio-addons/addon-jupyterlab/issues/319.
Please provide logs and check them.

**Comment by frenck** [comment] 2022-09-15 15:50
Fixed in https://github.com/hassio-addons/addon-jupyterlab/releases/tag/v0.8.2

**Closed by frenck** 2022-09-15 15:50 UTC
