### ISSUE TITLE
502 error in 0.8.2

### ISSUE THREAD

**Issue by michael5411** [hassio-addons/addon-jupyterlab#332] opened 2022-09-16 16:05 UTC
# Problem/Motivation

Web interface does not open; same problem as with 0.8.1

Tried:
- clear browser cache
- use different browser (tested Chrome and Safari)
- restart Home Assistant
- reboot Home Assistant Server completely

no result

**Comment by tjorim** [comment] 2022-09-16 17:09
Duplicate of #324

**Closed** 2022-09-16 17:09 UTC
